test_that("mn_stats", {
  testdata <- random_datset(100)
  res <- mn_stats(
    indicators = list(
      indicator_iodine(),
      indicator_ferritin(adjustment_ferritin_cutoff()),
      indicator_anaemia(),
      indicator_ida()
    ),
    age = testdata$age_years,
    sex = testdata$sex,
    pregnancy_status = testdata$pregnancy_status,
    lactating_status = testdata$lactating_status,
    ferritin = testdata$ferritin_measurement,
    iodine = testdata$iodine,
    CRP = testdata$crp_measurement,
    AGP = testdata$agp_measurement,
    haemoglobin = testdata$haemoglobin_measurement,
    is_smoker = testdata$is_smoker,
    altitude = testdata$altitude,
    smokes_cigarettes_per_day = testdata$smokes_cigarettes_per_day,
    pregnancyweeks = testdata$pregnancyweeks,
    pregnancymonths = testdata$pregnancymonths,
    cluster = 1:nrow(testdata),
    strata = rep.int(1, nrow(testdata)),
    area = testdata$area
  )
  expect_true(is.data.frame(res))
  expect_true(nrow(res) > 0)
  expect_equal(
    colnames(res),
    c(
      "Group",
      "age_start",
      "age_end",
      "age_unit",
      "iodine_pop",
      "iodine_unwpop",
      "iodine_mean",
      "iodine_median_r",
      "iodine_25percentile",
      "iodine_75percentile",
      "ferritin_unadj_pop",
      "ferritin_unadj_unwpop",
      "ferritin_unadj_mean",
      "ferritin_unadj_mean_sd",
      "ferritin_unadj_mean_ll",
      "ferritin_unadj_mean_ul",
      "ferritin_unadj_25percentile",
      "ferritin_unadj_50percentile",
      "ferritin_unadj_75percentile",
      "depletedironstores_unadj_r",
      "depletedironstores_unadj_se",
      "depletedironstores_unadj_ll",
      "depletedironstores_unadj_ul",
      "riskofironoverload_unadj_r",
      "riskofironoverload_unadj_se",
      "riskofironoverload_unadj_ll",
      "riskofironoverload_unadj_ul",
      "ferritin_adj_pop",
      "ferritin_adj_unwpop",
      "ferritin_adj_mean",
      "ferritin_adj_mean_sd",
      "ferritin_adj_mean_ll",
      "ferritin_adj_mean_ul",
      "ferritin_adj_25percentile",
      "ferritin_adj_50percentile",
      "ferritin_adj_75percentile",
      "depletedironstores_adj_r",
      "depletedironstores_adj_se",
      "depletedironstores_adj_ll",
      "depletedironstores_adj_ul",
      "riskofironoverload_adj_r",
      "riskofironoverload_adj_se",
      "riskofironoverload_adj_ll",
      "riskofironoverload_adj_ul",
      "hgb_pop",
      "hgb_unwpop",
      "hgb_mean",
      "hgb_mean_sd",
      "hgb_mean_ll",
      "hgb_mean_ul",
      "hgb_25percentile",
      "hgb_50percentile",
      "hgb_75percentile",
      "totalanaemia_r",
      "totalanaemia_se",
      "totalanaemia_ll",
      "totalanaemia_ul",
      "mildanaemia_r",
      "mildanaemia_se",
      "mildanaemia_ll",
      "mildanaemia_ul",
      "moderateanaemia_r",
      "moderateanaemia_se",
      "moderateanaemia_ll",
      "moderateanaemia_ul",
      "severeanaemia_r",
      "severeanaemia_se",
      "severeanaemia_ll",
      "severeanaemia_ul",
      "ida_unadj_pop",
      "ida_unadj_unwpop",
      "ida_unadj_r",
      "ida_unadj_se",
      "ida_unadj_ll",
      "ida_unadj_ul",
      "ida_adj_pop",
      "ida_adj_unwpop",
      "ida_adj_r",
      "ida_adj_se",
      "ida_adj_ll",
      "ida_adj_ul"
    )
  )
  expect_true(
    all(c("Area: Urban", "Area: Rural") %in% res$Group)
  )
})
